services:
  db:
    image: postgres:17
    restart: unless-stopped
    #ports:
      #- "5432:5432" #Questionable - only expose if needed
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - logs_postgres:/var/log/postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env.prod
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5


  django-web:
    build: .
    restart: unless-stopped
    container_name: django-docker
    depends_on:
      db:
        condition: service_healthy

    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
      - logs_django:/var/log/django
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env.prod

  frontend-proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/static:ro
      - media_data:/media:ro
      - logs_nginx:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - django-web

volumes:
  postgres_data:
  media_data:
  static_data:
  logs_postgres:
  logs_django:
  logs_nginx: